// 24 canonical Vedic mantras — generated from scripts/mantras-master-list.json
// via scripts/mantras-build-ts.cjs. Edit the JSON and re-run the script;
// do not edit this file by hand.
//
// Each entry pairs the chant (Devanagari + IAST + English) with a yantra
// brief for the production template, a one-line meaning, deeper context,
// recommended timing, and per-video chant counts so the master list
// doubles as the YouTube Shorts production manifest.

export type MantraCategory =
  | "foundational"
  | "solar"
  | "healing"
  | "invocation-devata"
  | "vishnu"
  | "knowledge"
  | "abundance"
  | "protection"
  | "courage"
  | "universal-peace"
  | "daily-ritual"
  | "brahman";

export type MantraLengthClass = "short" | "medium" | "long";

export interface MantraYantra {
  /** Traditional name of the yantra (Sri Yantra, Ganesha Yantra, etc.). */
  name: string;
  /** Plain-English visual brief for the AE / Lottie template designer. */
  visualBrief: string;
}

export interface MantraText {
  devanagari: string;
  iast: string;
  /** Short English translation suitable for an on-screen subtitle. */
  english: string;
}

export interface MantraVideo {
  lengthClass: MantraLengthClass;
  /** Length of ONE recitation of the mantra, in seconds. */
  chantDurationSec: number;
  /** How many times the mantra is chanted in the short. */
  repetitions: number;
  /** Target finished length of the YouTube short, in seconds. */
  videoTargetSec: number;
}

export interface Mantra {
  slug: string;
  title: string;
  sanskritName: string;
  category: MantraCategory;
  devata: string;
  yantra: MantraYantra;
  text: MantraText;
  /** One-sentence summary suitable for a card preview. */
  meaningOneLine: string;
  /** 2-4 sentence deeper explanation surfacing on the detail card. */
  context: string;
  whenToChant: string;
  /** Optional pillar slug — surfaces this mantra on the matching pillar page. */
  pillarSlug?: string;
  video: MantraVideo;
}

export const MANTRAS: Mantra[] = [
  {
    slug: "om-pranava",
    title: "Om — The Pranava",
    sanskritName: "Praṇava",
    category: "foundational",
    devata: "Brahman / the unmanifest source",
    yantra: {
      name: "Pranava Yantra",
      visualBrief:
        "The Om glyph itself rendered as gold-on-saffron, slowly rotating, with a single golden bindu (dot) at the crescent. Concentric breath-rings expand on each utterance.",
    },
    text: {
      devanagari: "ॐ",
      iast: "Oṁ",
      english: "The primordial sound. The seed of all mantras.",
    },
    meaningOneLine:
      "The seed-syllable from which all sound and creation arise.",
    context:
      "Patanjali (1.27) identifies Om as the sound-name of Ishvara, and 1.28 prescribes its repetition with contemplation of meaning. The Mandukya Upanishad devotes itself entirely to unfolding the four parts of Om — A, U, M, and the silence after. Every mantra in this library begins and ends with it.",
    whenToChant: "Always — opens and closes every practice. Three Oms before meditation; one Om before any other mantra.",
    pillarSlug: "brahman-connection",
    video: {
      lengthClass: "short",
      chantDurationSec: 4,
      repetitions: 3,
      videoTargetSec: 30,
    },
  },
  {
    slug: "om-shanti-mantra",
    title: "Om Shanti Shanti Shantih",
    sanskritName: "Śānti Mantra",
    category: "universal-peace",
    devata: "Shanti (peace) personified",
    yantra: {
      name: "Lotus-Peace Yantra",
      visualBrief:
        "An eight-petalled white lotus on cream background, each petal labelled with one realm receiving peace. Soft amber halo pulses outward on each 'Shantih'.",
    },
    text: {
      devanagari: "ॐ शान्तिः शान्तिः शान्तिः",
      iast: "Oṁ Śāntiḥ Śāntiḥ Śāntiḥ",
      english: "Peace within. Peace around. Peace everywhere.",
    },
    meaningOneLine:
      "Three peace-invocations addressed to three realms — body/mind, the immediate environment, and the universe.",
    context:
      "Every Upanishad closes with this triple Shanti — first for adhyatmika (internal afflictions), then adhibhautika (external/elemental), then adhidaivika (cosmic/divine) sources of disturbance. It is the closing seal of every Vedic practice.",
    whenToChant: "At the end of every meditation, every sandhya, and every chanting session. Three times slowly, the third drawn out longest.",
    pillarSlug: "sandhya-meditation",
    video: {
      lengthClass: "short",
      chantDurationSec: 7,
      repetitions: 3,
      videoTargetSec: 35,
    },
  },
  {
    slug: "gayatri-mantra",
    title: "Gayatri Mantra",
    sanskritName: "Gāyatrī Mahāmantra",
    category: "solar",
    devata: "Savitur (the supreme solar light)",
    yantra: {
      name: "Gayatri Yantra",
      visualBrief:
        "Twenty-four-petalled solar disc (one petal per syllable of the mantra), with a six-pointed star centre containing the seed Hrīṁ. Sunrise gradient from horizon-orange to noon-gold to violet.",
    },
    text: {
      devanagari: "ॐ भूर्भुवः स्वः । तत्सवितुर्वरेण्यं भर्गो देवस्य धीमहि । धियो यो नः प्रचोदयात् ॥",
      iast: "Oṁ Bhūr Bhuvaḥ Svaḥ | Tat Savitur Vareṇyaṁ Bhargo Devasya Dhīmahi | Dhiyo Yo Naḥ Pracodayāt ||",
      english: "We meditate on the supreme effulgence of the divine Sun. May it illumine our intellects.",
    },
    meaningOneLine:
      "A prayer addressed to the supreme light hidden inside the sun to awaken right understanding in the practitioner.",
    context:
      "Rig Veda 3.62.10. Composed by the sage Vishvamitra and considered the mother of all mantras. Traditionally chanted at the three sandhyas — sunrise, noon, sunset — facing the sun. Twenty-four syllables, twenty-four petals on its yantra, and 108 repetitions is the classical count.",
    whenToChant: "Three sandhyas (sunrise, solar noon, sunset). Minimum 9 repetitions; ideal 27 or 108.",
    pillarSlug: "sandhya-meditation",
    video: {
      lengthClass: "long",
      chantDurationSec: 22,
      repetitions: 1,
      videoTargetSec: 55,
    },
  },
  {
    slug: "mahamrityunjaya-mantra",
    title: "Mahamrityunjaya — The Great Conquest-of-Death Mantra",
    sanskritName: "Mahāmṛtyuñjaya Mantra",
    category: "healing",
    devata: "Shiva (Tryambaka, the three-eyed)",
    yantra: {
      name: "Mahamrityunjaya Yantra",
      visualBrief:
        "Concentric triangles (inward-pointing for Shakti, outward for Shiva) around a central trident-bindu. Violet-and-silver palette. A slow inhale-exhale pulse on the outer ring.",
    },
    text: {
      devanagari: "ॐ त्र्यम्बकं यजामहे सुगन्धिं पुष्टिवर्धनम् । उर्वारुकमिव बन्धनान्मृत्योर्मुक्षीय माऽमृतात् ॥",
      iast: "Oṁ Tryambakaṁ Yajāmahe Sugandhiṁ Puṣṭivardhanam | Urvārukamiva Bandhanānmṛtyormukṣīya Māmṛtāt ||",
      english: "We worship the three-eyed one, fragrant and nourishing. As the ripe cucumber falls free from its vine, may we be freed from death — not from immortality.",
    },
    meaningOneLine:
      "A prayer to Shiva for healing and liberation from the fear of death — letting go as naturally as fruit ripens off the vine.",
    context:
      "Rig Veda 7.59.12 — also called the Tryambakam mantra. Traditionally chanted for healing, longevity, and protection from accidents. The image of the urvāruka (ripe cucumber) detaching effortlessly is the central teaching: liberation arrives not by force but by ripeness.",
    whenToChant: "For self or others in illness, before surgery, during recovery, or as a daily healing practice. 11 or 108 repetitions.",
    pillarSlug: "healing-meditation",
    video: {
      lengthClass: "long",
      chantDurationSec: 25,
      repetitions: 1,
      videoTargetSec: 60,
    },
  },
  {
    slug: "panchakshari-namah-shivaya",
    title: "Om Namah Shivaya — The Five-Syllable Shiva Mantra",
    sanskritName: "Pañcākṣarī Mantra",
    category: "foundational",
    devata: "Shiva",
    yantra: {
      name: "Shiva Yantra",
      visualBrief:
        "Stylized lingam (vertical column emerging from a circular base — geometric, NOT photographic) inside a downward-pointing triangle. Indigo-silver palette with a crescent-moon glow.",
    },
    text: {
      devanagari: "ॐ नमः शिवाय",
      iast: "Oṁ Namaḥ Śivāya",
      english: "I bow to Shiva — the auspicious one within.",
    },
    meaningOneLine:
      "Five syllables (na-ma-śi-vā-ya) corresponding to the five elements, returning the practitioner to elemental simplicity.",
    context:
      "Considered the supreme Shiva mantra in the Shaiva tradition. Each syllable governs one element: na (earth), ma (water), śi (fire), vā (air), ya (ether). Repeated, the mantra returns the practitioner to elemental ground — the felt sense of being made of the same stuff as the universe.",
    whenToChant: "Morning practice, before meditation, or any moment of agitation. 108 repetitions on a rudraksha mala is traditional.",
    pillarSlug: "thoughts-intention",
    video: {
      lengthClass: "short",
      chantDurationSec: 5,
      repetitions: 3,
      videoTargetSec: 35,
    },
  },
  {
    slug: "dvadashakshari-vasudeva",
    title: "Om Namo Bhagavate Vasudevaya — The Twelve-Syllable Vishnu Mantra",
    sanskritName: "Dvādaśākṣarī Mantra",
    category: "vishnu",
    devata: "Vishnu / Vasudeva (Krishna's father-name)",
    yantra: {
      name: "Sudarshana Yantra",
      visualBrief:
        "Sudarshana chakra — six-pointed star formed by two interlocking triangles, surrounded by 16-petalled lotus, with concentric flame-rings. Deep blue and gold.",
    },
    text: {
      devanagari: "ॐ नमो भगवते वासुदेवाय",
      iast: "Oṁ Namo Bhagavate Vāsudevāya",
      english: "I bow to the divine Vasudeva, who indwells all beings.",
    },
    meaningOneLine:
      "A twelve-syllable mantra of full surrender to Vishnu as the inner self of all that lives.",
    context:
      "Cited in the Bhagavata Purana as the supreme mantra. Twelve syllables map to the twelve months and the twelve solar movements. Often chanted by devotees of Krishna alongside the Hare Krishna Mahamantra.",
    whenToChant: "Morning sankalpa, evening before sleep, before meals. 108 repetitions ideal; even 12 will mark the day.",
    pillarSlug: "brahman-connection",
    video: {
      lengthClass: "medium",
      chantDurationSec: 8,
      repetitions: 3,
      videoTargetSec: 45,
    },
  },
  {
    slug: "hare-krishna-maha-mantra",
    title: "Hare Krishna Maha Mantra",
    sanskritName: "Mahāmantra",
    category: "vishnu",
    devata: "Radha-Krishna (the divine couple)",
    yantra: {
      name: "Yugala Yantra",
      visualBrief:
        "Twin-lotus yantra — two interpenetrating lotuses, one rose-gold (Radha), one peacock-blue (Krishna), sharing a single bindu at centre. Soft pink-and-saffron halo.",
    },
    text: {
      devanagari: "हरे कृष्ण हरे कृष्ण कृष्ण कृष्ण हरे हरे । हरे राम हरे राम राम राम हरे हरे ॥",
      iast: "Hare Kṛṣṇa Hare Kṛṣṇa Kṛṣṇa Kṛṣṇa Hare Hare | Hare Rāma Hare Rāma Rāma Rāma Hare Hare ||",
      english: "O divine energy (Hare), O Krishna, O Rama — please engage me in your loving service.",
    },
    meaningOneLine:
      "A sixteen-name maha-mantra calling the divine feminine (Hare/Radha) and the divine masculine (Krishna, Rama) into intimate presence.",
    context:
      "Kali-Santarana Upanishad names this as the antidote to the suffering of the Kali age. Popularized worldwide by the Gaudiya Vaishnava tradition. Sweet, repeatable, builds devotion through sheer iteration.",
    whenToChant: "Anytime — walking, cooking, driving, before sleep. The mantra that bears infinite repetition without losing flavour.",
    pillarSlug: "divine-manifestation",
    video: {
      lengthClass: "long",
      chantDurationSec: 18,
      repetitions: 2,
      videoTargetSec: 55,
    },
  },
  {
    slug: "ganesha-invocation",
    title: "Om Gam Ganapataye Namaha",
    sanskritName: "Gaṇeśa Bīja Mantra",
    category: "invocation-devata",
    devata: "Ganesha (Ganapati)",
    yantra: {
      name: "Ganesha Yantra",
      visualBrief:
        "Eight-petalled lotus surrounding a downward-pointing triangle, with the seed Gaṁ at centre and a stylized trunk-curve at the bindu. Vermillion + saffron + ivory.",
    },
    text: {
      devanagari: "ॐ गं गणपतये नमः",
      iast: "Oṁ Gaṁ Gaṇapataye Namaḥ",
      english: "I bow to Ganapati — the remover of obstacles.",
    },
    meaningOneLine:
      "The seed-mantra (Gaṁ) of Ganesha invokes the energy that clears the path before any undertaking.",
    context:
      "Chanted at the start of every Vedic ritual, every new venture, every journey. The convention is to invoke Ganesha first so the rest of the practice proceeds unimpeded. Twenty-one repetitions is the auspicious count.",
    whenToChant: "Before starting any practice, project, exam, or journey. First thing on waking on a difficult day.",
    pillarSlug: "morning-initiation",
    video: {
      lengthClass: "short",
      chantDurationSec: 6,
      repetitions: 3,
      videoTargetSec: 35,
    },
  },
  {
    slug: "vakratunda-mahakaya",
    title: "Vakratunda Mahakaya — Ganesha Invocation Verse",
    sanskritName: "Vakratuṇḍa Mahākāya Mantra",
    category: "invocation-devata",
    devata: "Ganesha (Ganapati)",
    yantra: {
      name: "Ganesha Yantra (extended)",
      visualBrief:
        "Same Ganesha yantra as above but with a Surya-koti (a million suns) corona burst behind the lotus, since the verse compares Ganesha's radiance to a crore of suns.",
    },
    text: {
      devanagari: "वक्रतुण्ड महाकाय सूर्यकोटि समप्रभ । निर्विघ्नं कुरु मे देव सर्वकार्येषु सर्वदा ॥",
      iast: "Vakratuṇḍa Mahākāya Sūryakoṭi Samaprabha | Nirvighnaṁ Kuru Me Deva Sarvakāryeṣu Sarvadā ||",
      english: "O curved-trunked, mighty-bodied one, radiant as a million suns — clear the obstacles from all my endeavours, always.",
    },
    meaningOneLine:
      "The full-form Ganesha invocation — a request that all work, today and forever, proceed without obstruction.",
    context:
      "The most commonly recited verse before the start of any project, business launch, journey, or learning. Pair with the seed mantra: chant Vakratunda once, follow with 11 or 21 repetitions of Om Gam Ganapataye Namaha.",
    whenToChant: "Before any major beginning — a new month, new project, school year, marriage, or move.",
    pillarSlug: "morning-initiation",
    video: {
      lengthClass: "medium",
      chantDurationSec: 14,
      repetitions: 2,
      videoTargetSec: 50,
    },
  },
  {
    slug: "saraswati-bija",
    title: "Om Aim Saraswatyai Namaha",
    sanskritName: "Sarasvatī Bīja Mantra",
    category: "knowledge",
    devata: "Saraswati",
    yantra: {
      name: "Saraswati Yantra",
      visualBrief:
        "Eight-petalled white lotus on still water, with the seed Aiṁ at centre and a quill-curve at the bindu. Pearl-white, swan-grey, and pale gold.",
    },
    text: {
      devanagari: "ॐ ऐं सरस्वत्यै नमः",
      iast: "Oṁ Aiṁ Sarasvatyai Namaḥ",
      english: "I bow to Saraswati — the goddess of speech, music, and wisdom.",
    },
    meaningOneLine:
      "The seed-mantra (Aiṁ) invokes Saraswati's blessing for clarity of speech, study, and the arts.",
    context:
      "Chanted by students before exams, by writers before composing, by musicians before performing, and by anyone learning a new skill. The seed Aiṁ is associated with the throat chakra and speech.",
    whenToChant: "Before study, before writing, before speaking publicly, before any creative act. 108 repetitions before a major exam or recital.",
    pillarSlug: "thoughts-intention",
    video: {
      lengthClass: "short",
      chantDurationSec: 6,
      repetitions: 3,
      videoTargetSec: 35,
    },
  },
  {
    slug: "saraswati-vandana",
    title: "Ya Kundendu Tushara Hara Dhavala — Saraswati Vandana",
    sanskritName: "Sarasvatī Vandanā",
    category: "knowledge",
    devata: "Saraswati",
    yantra: {
      name: "Saraswati Yantra (extended)",
      visualBrief:
        "Saraswati yantra with a stylized veena-form (two parallel curves crossed by strings) replacing the bindu. White lotus on dark-water gradient.",
    },
    text: {
      devanagari: "या कुन्देन्दु तुषारहार धवला या शुभ्र वस्त्रावृता । या वीणा वरदण्ड मण्डितकरा या श्वेत पद्मासना ॥",
      iast: "Yā Kundendu Tuṣārahāra Dhavalā Yā Śubhra Vastrāvṛtā | Yā Vīṇā Varadaṇḍa Maṇḍitakarā Yā Śveta Padmāsanā ||",
      english: "She who is white as jasmine, the moon, and pearl strands — clothed in pure white, hands graced with veena and the boon-giving rod, seated on a white lotus.",
    },
    meaningOneLine:
      "The full devotional verse of Saraswati — chanted by students across India before the start of school assemblies and recitals.",
    context:
      "From the Saraswati Stotra. The whiteness imagery is a teaching: Saraswati is sattvic intelligence, untouched by the colours of rajas (passion) and tamas (dullness). Two more verses traditionally follow; the opening verse is enough for daily practice.",
    whenToChant: "Start of academic year, before any sustained period of study, before public speaking.",
    pillarSlug: "thoughts-intention",
    video: {
      lengthClass: "long",
      chantDurationSec: 20,
      repetitions: 1,
      videoTargetSec: 55,
    },
  },
  {
    slug: "lakshmi-bija",
    title: "Om Shrim Maha Lakshmiyai Namaha",
    sanskritName: "Lakṣmī Bīja Mantra",
    category: "abundance",
    devata: "Maha Lakshmi",
    yantra: {
      name: "Sri Yantra",
      visualBrief:
        "Sri Yantra — nine interlocking triangles forming 43 smaller triangles, surrounded by a 16-petal then 8-petal lotus, then a triple square gateway. The most complex yantra in the canon. Gold-on-deep-rose.",
    },
    text: {
      devanagari: "ॐ श्रीं महालक्ष्म्यै नमः",
      iast: "Oṁ Śrīṁ Mahālakṣmyai Namaḥ",
      english: "I bow to Maha Lakshmi — the source of all flourishing.",
    },
    meaningOneLine:
      "The seed-mantra (Śrīṁ) invokes Lakshmi's blessing for material and inner abundance.",
    context:
      "Lakshmi governs not just wealth but every form of flourishing — health, beauty, harmony, dharmic prosperity. The Sri Yantra is the most sacred geometric form in Sri Vidya, said to contain the entire cosmos. Friday is Lakshmi's day; the practice intensifies on Friday evenings.",
    whenToChant: "Friday evening practice; before financial decisions, business launches, or any matter requiring grace and flow. 108 repetitions on Friday.",
    pillarSlug: "divine-manifestation",
    video: {
      lengthClass: "short",
      chantDurationSec: 7,
      repetitions: 3,
      videoTargetSec: 40,
    },
  },
  {
    slug: "durga-bija",
    title: "Om Dum Durgayei Namaha",
    sanskritName: "Durgā Bīja Mantra",
    category: "protection",
    devata: "Durga",
    yantra: {
      name: "Durga Yantra",
      visualBrief:
        "Nine-pointed star (Navakona) within a 16-petal lotus, surrounded by the seed Duṁ in eight cardinal points. Vermilion, gold, and deep-orange palette — the colours of fire.",
    },
    text: {
      devanagari: "ॐ दुं दुर्गायै नमः",
      iast: "Oṁ Duṁ Durgāyai Namaḥ",
      english: "I bow to Durga — the unconquerable protectress.",
    },
    meaningOneLine:
      "The seed-mantra (Duṁ) invokes Durga as the fierce protective power that dissolves what threatens the seeker.",
    context:
      "Chanted for protection from external harm and internal fear. The literal meaning of durga is 'fort' or 'hard to access' — what is yours behind her gates cannot be reached by what would harm it. Navaratri's nine nights are dedicated to her nine forms.",
    whenToChant: "When facing fear, threat, or hostility — internal or external. Daily during Navaratri (twice a year, March-April and September-October). 108 repetitions.",
    pillarSlug: "thoughts-intention",
    video: {
      lengthClass: "short",
      chantDurationSec: 6,
      repetitions: 3,
      videoTargetSec: 35,
    },
  },
  {
    slug: "hanuman-mantra",
    title: "Om Hanumate Namaha",
    sanskritName: "Hanuman Bīja Mantra",
    category: "courage",
    devata: "Hanuman",
    yantra: {
      name: "Hanuman Yantra",
      visualBrief:
        "Stylized mace (gada) standing upright at centre, surrounded by twelve flame-petals and a square gateway with bīja-syllables at the four entries. Saffron-orange dominant, with red accents.",
    },
    text: {
      devanagari: "ॐ हनुमते नमः",
      iast: "Oṁ Hanumate Namaḥ",
      english: "I bow to Hanuman — the lord of strength and devotion.",
    },
    meaningOneLine:
      "Invokes the unwavering strength and selfless devotion that Hanuman embodies — courage in service of something larger than the self.",
    context:
      "Hanuman is the patron of physical strength, mental endurance, and absolute devotion (bhakti). Chanted by athletes, soldiers, devotees facing trials, and anyone needing courage. Tuesday is his day. The full Hanuman Chalisa is a richer practice for longer sessions; this seed mantra is the daily anchor.",
    whenToChant: "Tuesday morning; before athletic events, difficult conversations, or any test of courage. 108 repetitions.",
    pillarSlug: "movement",
    video: {
      lengthClass: "short",
      chantDurationSec: 5,
      repetitions: 3,
      videoTargetSec: 30,
    },
  },
  {
    slug: "surya-bija",
    title: "Om Suryaya Namaha",
    sanskritName: "Sūrya Bīja Mantra",
    category: "solar",
    devata: "Surya (the Sun)",
    yantra: {
      name: "Surya Yantra",
      visualBrief:
        "Twelve-petalled solar disc (one petal per zodiac sign and per sun-name), with a central bindu radiating twelve golden rays. Pure gold on rising-sun gradient.",
    },
    text: {
      devanagari: "ॐ सूर्याय नमः",
      iast: "Oṁ Sūryāya Namaḥ",
      english: "I bow to Surya — the visible source of life on earth.",
    },
    meaningOneLine:
      "The simplest direct invocation of the sun as the source of vitality, clarity, and order.",
    context:
      "Chanted with the twelve poses of Surya Namaskar — one of the twelve sun-names per pose. Cultivating gratitude toward the sun is, in Vedic terms, gratitude toward the source of all life on the planet. Sunday is Surya's day.",
    whenToChant: "Sunrise, paired with Surya Namaskar (one name per pose, the cycle returning to Surya at the close). Also Sunday morning practice.",
    pillarSlug: "movement",
    video: {
      lengthClass: "short",
      chantDurationSec: 4,
      repetitions: 3,
      videoTargetSec: 30,
    },
  },
  {
    slug: "asato-ma-prayer",
    title: "Asato Ma Sadgamaya — From Untruth Lead Me to Truth",
    sanskritName: "Pavamāna Mantra",
    category: "brahman",
    devata: "Brahman (the supreme truth)",
    yantra: {
      name: "Three-Stage Light Yantra",
      visualBrief:
        "Three concentric circles transitioning from deep indigo (untruth) → soft violet-gold (light) → pure pearl-white (immortality). Three lines of Devanagari arc around each ring.",
    },
    text: {
      devanagari: "ॐ असतो मा सद्गमय । तमसो मा ज्योतिर्गमय । मृत्योर्मा अमृतं गमय । ॐ शान्तिः शान्तिः शान्तिः ॥",
      iast: "Oṁ Asato Mā Sadgamaya | Tamaso Mā Jyotirgamaya | Mṛtyormā Amṛtaṁ Gamaya | Oṁ Śāntiḥ Śāntiḥ Śāntiḥ ||",
      english: "Lead me from untruth to truth. Lead me from darkness to light. Lead me from death to immortality. Om peace peace peace.",
    },
    meaningOneLine:
      "The shortest and most universal Vedic prayer — three movements from confusion to clarity, asked of the source within.",
    context:
      "Brihadaranyaka Upanishad 1.3.28. One of the oldest and most-translated lines in the Vedic corpus. The progression is not three separate requests — it is one request seen from three angles, the same movement viewed through cognitive, perceptual, and existential lenses.",
    whenToChant: "Morning sandhya, before meditation, before any moment of decision. Chanted slowly enough that each clause lands.",
    pillarSlug: "brahman-connection",
    video: {
      lengthClass: "long",
      chantDurationSec: 18,
      repetitions: 1,
      videoTargetSec: 50,
    },
  },
  {
    slug: "lokah-samastah",
    title: "Lokah Samastah Sukhino Bhavantu",
    sanskritName: "Lokāḥ Samastāḥ Sukhino Bhavantu",
    category: "universal-peace",
    devata: "The all-pervading good",
    yantra: {
      name: "Dharma-Chakra Universal Yantra",
      visualBrief:
        "Earth-globe outline at centre, surrounded by an eight-spoked dharma-chakra, surrounded by a wreath of small lotuses. Earth-blue, leaf-green, lotus-pink palette.",
    },
    text: {
      devanagari: "लोकाः समस्ताः सुखिनो भवन्तु",
      iast: "Lokāḥ Samastāḥ Sukhino Bhavantu",
      english: "May all beings everywhere be happy and free.",
    },
    meaningOneLine:
      "A wish so wide it contains every being — the practitioner included.",
    context:
      "Widely chanted at the close of yoga classes worldwide. The grammar is precise: all (samastāḥ) beings (lokāḥ), without exception, without a hierarchy of deserving. The phrase 'may the thoughts, words, and actions of my own life contribute in some way to that happiness and freedom for all' is the unspoken second half.",
    whenToChant: "Close of every yoga or meditation session; before sleep; before meals as the second half of Brahmarpanam.",
    pillarSlug: "gratitude",
    video: {
      lengthClass: "medium",
      chantDurationSec: 10,
      repetitions: 3,
      videoTargetSec: 50,
    },
  },
  {
    slug: "sarve-bhavantu-sukhinah",
    title: "Sarve Bhavantu Sukhinah",
    sanskritName: "Brihadāraṇyaka Śānti Pāṭha",
    category: "universal-peace",
    devata: "The universal welfare",
    yantra: {
      name: "Four-Direction Lotus Yantra",
      visualBrief:
        "Central lotus surrounded by four equally-sized lotuses at the four cardinal directions, each labelled with one of the four wishes (happiness, health, auspiciousness, freedom from suffering). Cream + sky-blue + soft amber.",
    },
    text: {
      devanagari: "सर्वे भवन्तु सुखिनः सर्वे सन्तु निरामयाः । सर्वे भद्राणि पश्यन्तु मा कश्चिद् दुःखभाग्भवेत् ॥",
      iast: "Sarve Bhavantu Sukhinaḥ Sarve Santu Nirāmayāḥ | Sarve Bhadrāṇi Paśyantu Mā Kaścid Duḥkhabhāgbhavet ||",
      english: "May all be happy. May all be free from illness. May all see auspiciousness. May no one suffer.",
    },
    meaningOneLine:
      "Four universal wishes: happiness, health, the seeing of beauty, freedom from sorrow — extended to every being without exception.",
    context:
      "The peace invocation of the Brihadaranyaka Upanishad. Like Lokah Samastah, but with four specific dimensions of well-being rather than one. The clauses build: from inner happiness, to outer health, to perception, to relief from suffering.",
    whenToChant: "Close of meditation; before family meals; in moments of conflict, when the practitioner needs to remember that the other person's well-being is part of the wish.",
    pillarSlug: "gratitude",
    video: {
      lengthClass: "long",
      chantDurationSec: 16,
      repetitions: 2,
      videoTargetSec: 55,
    },
  },
  {
    slug: "saha-nav-avatu",
    title: "Saha Nav Avatu — Together May We Be Nourished",
    sanskritName: "Taittirīya Śānti Pāṭha",
    category: "universal-peace",
    devata: "Guru-shishya (teacher-student bond)",
    yantra: {
      name: "Twin-Lotus Yantra",
      visualBrief:
        "Two facing lotuses on a single stem, with a shared bindu of golden light between them. Lamp-flame palette — saffron, gold, ochre.",
    },
    text: {
      devanagari: "ॐ सह नाववतु । सह नौ भुनक्तु । सह वीर्यं करवावहै । तेजस्विनावधीतमस्तु । मा विद्विषावहै ॥ ॐ शान्तिः शान्तिः शान्तिः ॥",
      iast: "Oṁ Saha Nāv Avatu | Saha Nau Bhunaktu | Saha Vīryaṁ Karavāvahai | Tejasvināv adhītam astu | Mā Vidviṣāvahai || Oṁ Śāntiḥ Śāntiḥ Śāntiḥ ||",
      english: "May we be protected together. May we be nourished together. May we work with great vigour together. May our study be illuminating. May there be no hatred between us.",
    },
    meaningOneLine:
      "The teacher-student peace mantra — extended easily to any pairing or community committed to a shared inner endeavour.",
    context:
      "Opens and closes every chanting of the Taittiriya Upanishad. Traditionally chanted by teacher and student together at the start of every lesson. In modern context, it is the perfect opening for any team, marriage, or community committed to mutual growth.",
    whenToChant: "Start of any class, mentoring session, partner practice, family gathering, or team meeting where shared good is intended.",
    pillarSlug: "gratitude",
    video: {
      lengthClass: "long",
      chantDurationSec: 20,
      repetitions: 1,
      videoTargetSec: 55,
    },
  },
  {
    slug: "karagre-vasate-lakshmi",
    title: "Karagre Vasate Lakshmi — Looking at Your Palms on Waking",
    sanskritName: "Karadarśana Mantra",
    category: "daily-ritual",
    devata: "Lakshmi, Saraswati, Govinda — all present in the practitioner's own hands",
    yantra: {
      name: "Palmar Yantra",
      visualBrief:
        "Two open palms facing the viewer with a small lotus at the fingertips, a small veena at the centre, and a small chakra at the wrist — exactly mirroring the mantra's geography. Sunrise-amber on cream.",
    },
    text: {
      devanagari: "कराग्रे वसते लक्ष्मीः करमध्ये सरस्वती । करमूले तु गोविन्दः प्रभाते करदर्शनम् ॥",
      iast: "Karāgre Vasate Lakṣmīḥ Karamadhye Sarasvatī | Karamūle Tu Govindaḥ Prabhāte Karadarśanam ||",
      english: "At the fingertips lives Lakshmi. At the middle of the hand, Saraswati. At the wrist, Govinda. So at dawn we behold our own hands.",
    },
    meaningOneLine:
      "The first words of the day, spoken while looking at your own open palms — a recognition that what you need most is already within reach.",
    context:
      "The classical Indian morning ritual. Before stepping out of bed, the practitioner rubs the palms together, opens them, and recites this verse — placing the day's tools (wealth, learning, divine presence) in their own hands. The simplest and most psychologically loaded mantra in the daily set.",
    whenToChant: "First thing on waking, every morning, before the feet touch the floor.",
    pillarSlug: "morning-initiation",
    video: {
      lengthClass: "medium",
      chantDurationSec: 12,
      repetitions: 2,
      videoTargetSec: 45,
    },
  },
  {
    slug: "brahmarpanam-pre-meal",
    title: "Brahmarpanam — Pre-Meal Offering",
    sanskritName: "Brahmārpaṇam (Bhagavad Gītā 4.24)",
    category: "daily-ritual",
    devata: "Brahman (the source) and Agni (the digestive fire)",
    yantra: {
      name: "Agni-Kalasha Yantra",
      visualBrief:
        "Stylized brass pot (kalasha) with a flame rising above it, surrounded by a circular wreath of small grains, fruits, and leaves. Brass + amber + cream palette.",
    },
    text: {
      devanagari: "ब्रह्मार्पणं ब्रह्म हविर्ब्रह्माग्नौ ब्रह्मणा हुतम् । ब्रह्मैव तेन गन्तव्यं ब्रह्मकर्मसमाधिना ॥",
      iast: "Brahmārpaṇaṁ Brahma Havirbrahmāgnau Brahmaṇā Hutam | Brahmaiva Tena Gantavyaṁ Brahmakarma Samādhinā ||",
      english: "The offering is Brahman. The substance offered is Brahman. It is offered into the fire of Brahman by Brahman. To Brahman alone the doer of such action goes.",
    },
    meaningOneLine:
      "Eating is reframed as an offering — the food, the eater, the act, and the destination are all one underlying reality.",
    context:
      "Bhagavad Gita 4.24. The classical pre-meal mantra in many Indian households. The verse collapses the duality of eater and food into a single field of action — turning every meal into yajna (sacred offering) rather than mere consumption.",
    whenToChant: "Before every meal. Hands joined, eyes briefly closed, then begin eating mindfully.",
    pillarSlug: "nutrition-fasting",
    video: {
      lengthClass: "long",
      chantDurationSec: 17,
      repetitions: 1,
      videoTargetSec: 50,
    },
  },
  {
    slug: "tvameva-mata",
    title: "Tvameva Mata Cha Pita Tvameva — Universal Kinship",
    sanskritName: "Tvameva Mātā Stotra",
    category: "universal-peace",
    devata: "The Divine as everything in the practitioner's life",
    yantra: {
      name: "Six-Pointed Star Yantra",
      visualBrief:
        "Two interlocking triangles forming a six-pointed star (Shakti + Shiva union), with a central bindu and four cardinal lotus-tips representing the four relationships named in the verse — mother, father, friend, kin. Rose-gold + indigo palette.",
    },
    text: {
      devanagari: "त्वमेव माता च पिता त्वमेव त्वमेव बन्धुश्च सखा त्वमेव । त्वमेव विद्या द्रविणं त्वमेव त्वमेव सर्वं मम देव देव ॥",
      iast: "Tvameva Mātā Ca Pitā Tvameva | Tvameva Bandhuśca Sakhā Tvameva | Tvameva Vidyā Draviṇaṁ Tvameva | Tvameva Sarvaṁ Mama Deva Deva ||",
      english: "You alone are my mother and father. You alone are my friend and kin. You alone are my learning and my wealth. You alone are everything to me, my God of gods.",
    },
    meaningOneLine:
      "A full-surrender prayer — every relationship and every resource the practitioner depends on is the same divine source seen through different faces.",
    context:
      "A widely-recited devotional verse used in many Hindu households as a closing or all-encompassing prayer. Particularly powerful in seasons of loss — when an actual mother, father, or friend is absent, the verse remembers that the love itself never was theirs alone.",
    whenToChant: "Evening practice; moments of loneliness or loss; closing of a long meditation session.",
    pillarSlug: "brahman-connection",
    video: {
      lengthClass: "long",
      chantDurationSec: 18,
      repetitions: 1,
      videoTargetSec: 50,
    },
  },
  {
    slug: "purnamadah-purnamidam",
    title: "Om Purnamadah Purnamidam — The Fullness Invocation",
    sanskritName: "Pūrṇa Mantra (Īśa Upaniṣad)",
    category: "brahman",
    devata: "Brahman (the fullness)",
    yantra: {
      name: "Purna Kalasha Yantra",
      visualBrief:
        "An overflowing brass vessel (kalasha) at centre, with golden water cascading over its lip in an unbroken curve — the cascade returning to fill the same vessel from below. Mobius-like loop. Gold + cream palette.",
    },
    text: {
      devanagari: "ॐ पूर्णमदः पूर्णमिदं पूर्णात्पूर्णमुदच्यते । पूर्णस्य पूर्णमादाय पूर्णमेवावशिष्यते ॥ ॐ शान्तिः शान्तिः शान्तिः ॥",
      iast: "Oṁ Pūrṇamadaḥ Pūrṇamidaṁ Pūrṇāt Pūrṇamudacyate | Pūrṇasya Pūrṇamādāya Pūrṇamevāvaśiṣyate || Oṁ Śāntiḥ Śāntiḥ Śāntiḥ ||",
      english: "That is full. This is full. From fullness, fullness emerges. Take fullness from fullness, and fullness alone remains.",
    },
    meaningOneLine:
      "The most famous Vedic statement about non-duality — what is whole gives rise to wholeness, and remains whole.",
    context:
      "Invocation of the Isha Upanishad and several other Upanishads. The first and most influential teaching on the non-arithmetical nature of the Infinite: fullness minus fullness equals fullness. Pair with the Brahmarpanam pre-meal as a reminder that even consumption does not diminish the source.",
    whenToChant: "Opening of meditation; close of a Vedanta study session; before significant decisions about giving (charity, time, energy).",
    pillarSlug: "brahman-connection",
    video: {
      lengthClass: "long",
      chantDurationSec: 20,
      repetitions: 1,
      videoTargetSec: 55,
    },
  },
  {
    slug: "om-tat-sat",
    title: "Om Tat Sat — The Triple Designation of Brahman",
    sanskritName: "Oṁ Tat Sat (Bhagavad Gītā 17.23)",
    category: "brahman",
    devata: "Brahman (the absolute)",
    yantra: {
      name: "Triple-Circle Yantra",
      visualBrief:
        "Three concentric circles labelled Sat (being), Chit (awareness), Ananda (bliss) — with the central bindu shared by all three. Gold-on-cream, the simplest yantra in the set, intentionally.",
    },
    text: {
      devanagari: "ॐ तत् सत्",
      iast: "Oṁ Tat Sat",
      english: "Om. That. Truth.",
    },
    meaningOneLine:
      "Three syllables that name Brahman three different ways — as the sacred sound, as that which is pointed to, as the only thing that ultimately is.",
    context:
      "Bhagavad Gita 17.23 introduces this as the triple-designation of Brahman: 'Om Tat Sat — this is the three-fold name of Brahman, by which were ordained of old the Brahmanas, the Vedas, and sacrifices.' Traditionally appended to the close of any selfless action as a seal: this is offered, this is real, this is enough.",
    whenToChant: "After any act of selfless service, charity, or completed practice — as the closing seal that releases attachment to the act.",
    pillarSlug: "brahman-connection",
    video: {
      lengthClass: "short",
      chantDurationSec: 4,
      repetitions: 5,
      videoTargetSec: 30,
    },
  },
];

export function getMantraBySlug(slug: string): Mantra | undefined {
  return MANTRAS.find((m) => m.slug === slug);
}

export function getMantrasByPillar(pillarSlug: string): Mantra[] {
  return MANTRAS.filter((m) => m.pillarSlug === pillarSlug);
}

export function getMantrasByCategory(category: MantraCategory): Mantra[] {
  return MANTRAS.filter((m) => m.category === category);
}
